function pgAgents(){
var w=ws();
var cards=w.agents.map(function(a){
var kbCount=w.kb.filter(function(k){return k.agentId===a.id}).length;
return '<div class="glass rounded-2xl p-6 hover:border-tiffany-500/40 transition"><div class="flex items-start gap-4"><img src="'+(a.avatar||AVT[0])+'" class="w-14 h-14 rounded-2xl object-cover border border-ink-700" alt="" onerror="this.style.display=\'none\'"><div class="flex-1 min-w-0"><h3 class="font-display font-bold">'+esc(a.name)+'</h3><p class="text-xs text-ink-500 mt-0.5">'+esc(a.model)+' • '+esc(a.tone)+'</p></div><button data-action="edit-agent" data-id="'+a.id+'" class="p-2 text-ink-400 hover:text-white hover:bg-ink-800 rounded-lg">'+icon('edit','w-4 h-4')+'</button><button data-action="del-agent" data-id="'+a.id+'" class="p-2 text-red-400 hover:bg-red-500/10 rounded-lg">'+icon('trash','w-4 h-4')+'</button></div><p class="text-sm text-ink-400 leading-6 mt-3 line-clamp-2">'+esc(a.desc)+'</p><div class="flex items-center gap-2 mt-4 text-[11px] text-ink-500 flex-wrap"><span class="bg-ink-850 border border-ink-800 rounded-full px-2.5 py-1">'+esc(a.language)+'</span><span class="bg-ink-850 border border-ink-800 rounded-full px-2.5 py-1">'+kbCount+' مصدر معرفة</span><span class="bg-ink-850 border border-ink-800 rounded-full px-2.5 py-1">'+w.convos.filter(function(c){return c.agentId===a.id}).length+' محادثة</span><span class="bg-ink-850 border border-ink-800 rounded-full px-2.5 py-1">'+w.widgets.filter(function(x){return x.agentId===a.id}).length+' Widget</span></div></div>'}).join('');
return '<div class="flex items-center justify-between mb-5 flex-wrap gap-3"><p class="text-sm text-ink-400">'+w.agents.length+' من '+PLANS[w.plan].agents+' Agents في خطتك '+PLANS[w.plan].name+(isRemote()?' — الحد مفروض أيضًا من قاعدة البيانات':'')+'</p><button data-action="new-agent" class="btn-primary">'+icon('plus','w-4 h-4')+' Agent جديد</button></div><div class="grid md:grid-cols-2 gap-4">'+(cards||'<div class="md:col-span-2 glass rounded-2xl p-14 text-center text-ink-500">لا يوجد Agents بعد.<br><button data-action="new-agent" class="btn-primary mt-4">أنشئ أول Agent</button></div>')+'</div>';}

function agentOptions(sel){return '<option value="">مشترك — كل الوكلاء (يُنسخ لكل وكيل)</option>'+ws().agents.map(function(a){return '<option value="'+a.id+'"'+(sel===a.id?' selected':'')+'>'+esc(a.name)+'</option>'}).join('')}

function agentModal(id){
var a=id?ws().agents.find(function(x){return x.id===id}):null;
var v=a||{name:'',desc:'',avatar:AVT[0],instructions:'',language:'العربية',tone:'ودي واحترافي',model:'gemini-2.5-flash-lite',welcome:'أهلًا بك 👋 كيف أقدر أساعدك؟',fallback:NO_INFO_MSG};
var avs=AV_LOCAL.map(function(u){return '<label class="cursor-pointer"><input type="radio" name="avatar" value="'+u+'" class="hidden peer" '+(v.avatar===u?'checked':'')+'><img src="'+u+'" class="w-12 h-12 rounded-xl object-cover border-2 peer-checked:border-tiffany-500 border-transparent"></label>'}).join('');
modal('<h3 class="font-display font-bold text-lg mb-5">'+(a?'تعديل':'إنشاء')+' Agent</h3><form id="f-agent" class="space-y-3"><input type="hidden" name="id" value="'+((a&&a.id)||'')+'"><label class="lbl2">اسم الـ Agent *<input name="name" required class="inp-s" value="'+esc(v.name)+'" placeholder="مثال: موظف المبيعات"></label><label class="lbl2">الوصف (شخصية المساعد)<input name="desc" class="inp-s" value="'+esc(v.desc)+'"></label><div class="text-xs text-ink-400 mb-1">Avatar</div><div class="flex gap-2 mb-1">'+avs+'</div><label class="lbl2">التعليمات: أسلوب الكلام، اللهجة، قواعد الإجابة، الممنوعات *<textarea name="instructions" required rows="4" class="inp-s" placeholder="أنت موظف مبيعات لمتجر...">'+esc(v.instructions)+'</textarea></label><div class="grid grid-cols-2 gap-3"><label class="lbl2">اللغة<select name="language" class="inp-s">'+['العربية','English','ثنائي اللغة'].map(function(l){return '<option '+(l===v.language?'selected':'')+'>'+l+'</option>'}).join('')+'</select></label><label class="lbl2">النبرة واللهجة<select name="tone" class="inp-s">'+['ودي واحترافي','رسمي','مرح','هادئ ومتعاطف','خليجي ودود'].map(function(l){return '<option '+(l===v.tone?'selected':'')+'>'+l+'</option>'}).join('')+'</select></label></div><label class="lbl2">النموذج (يُحفظ لكل Agent)<select name="model" class="inp-s">'+AI_MODELS.map(function(l){return '<option '+(l===v.model?'selected':'')+'>'+l+'</option>'}).join('')+'</select></label><label class="lbl2">رسالة الترحيب<input name="welcome" class="inp-s" value="'+esc(v.welcome)+'"></label><label class="lbl2">رسالة عدم المعرفة (Fallback)<input name="fallback" class="inp-s" value="'+esc(v.fallback)+'"></label><div class="flex gap-2 pt-2"><button class="btn-primary flex-1">حفظ الـ Agent</button><button type="button" data-action="modal-close" class="btn-ghost">إلغاء</button></div></form>');}
