function authNetFail(msg){
modal('<h3 class="font-display font-bold text-lg mb-2">تعذر الاتصال بالخادم</h3>'
+'<p class="text-sm text-ink-300 leading-7 mb-2">'+esc(arErr(msg))+'</p>'
+'<p class="text-xs text-ink-500 leading-6 mb-4">يمكنك إعادة المحاولة عند عودة الاتصال، أو المتابعة فورًا بالوضع المحلي حيث تُحفظ الحسابات والبيانات على جهازك.</p>'
+'<div class="flex gap-2"><button data-action="modal-close" class="btn-ghost flex-1">إغلاق وإعادة المحاولة</button><button data-action="local-mode" class="btn-primary flex-1">المتابعة بالوضع المحلي</button></div>');}

function renderAuth(mode){
var titles={login:['مرحبًا بعودتك','سجّل دخولك لمتابعة إدارة موظفيك الرقميين.'],signup:['أنشئ حسابك','مساحة عمل معزولة جاهزة خلال ثوانٍ.'],forgot:['استعادة كلمة المرور','أدخل بريدك وسنرسل رابط إعادة التعيين.']};
var form='';
var demoBtn='<button type="button" data-action="demo-enter" class="btn-ghost w-full !py-3 !border-dashed text-ink-300">'+icon('eye','w-4 h-4')+' الدخول كضيف بدون حساب (وضع تجريبي — يبقى محفوظًا)</button>';
if(mode==='login')form='<form id="f-login" class="space-y-4"><label class="lbl">البريد الإلكتروني<input name="email" type="email" required class="inp" placeholder="you@company.com"></label><label class="lbl">كلمة المرور<input name="pass" type="password" required class="inp" placeholder="••••••••"></label><div class="flex items-center justify-between text-sm"><a href="#/forgot" class="text-tiffany-400 hover:underline">نسيت كلمة المرور؟</a></div><button class="btn-primary w-full !py-3" id="b-login">تسجيل الدخول</button><p class="text-sm text-ink-400 text-center">ليس لديك حساب؟ <a class="text-tiffany-400 font-semibold" href="#/signup">أنشئ حسابًا</a></p></form><div class="my-4 flex items-center gap-3 text-[11px] text-ink-600"><span class="flex-1 h-px bg-ink-800"></span>أو<span class="flex-1 h-px bg-ink-800"></span></div>'+demoBtn;
if(mode==='signup')form='<form id="f-signup" class="space-y-4"><label class="lbl">الاسم الكامل<input name="name" required class="inp" placeholder="اسمك"></label><label class="lbl">اسم النشاط / الشركة<input name="company" required class="inp" placeholder="مثال: متجر النخبة"></label><label class="lbl">نوع النشاط<select name="type" class="inp">'+['متجر إلكتروني','شركة','عيادة','مطعم','صالون','عقارات','مكتب خدمات','مركز تدريب','أخرى'].map(function(t){return '<option>'+t+'</option>'}).join('')+'</select></label><label class="lbl">البريد الإلكتروني<input name="email" type="email" required class="inp" placeholder="you@company.com"></label><label class="lbl">كلمة المرور<input name="pass" type="password" minlength="6" required class="inp" placeholder="6 أحرف على الأقل"></label><button class="btn-primary w-full !py-3" id="b-signup">إنشاء الحساب والبدء</button><p class="text-sm text-ink-400 text-center">لديك حساب؟ <a class="text-tiffany-400 font-semibold" href="#/login">سجّل دخولك</a></p></form><div class="my-4 flex items-center gap-3 text-[11px] text-ink-600"><span class="flex-1 h-px bg-ink-800"></span>أو<span class="flex-1 h-px bg-ink-800"></span></div>'+demoBtn;
if(mode==='forgot')form='<form id="f-forgot" class="space-y-4"><label class="lbl">البريد الإلكتروني<input name="email" type="email" required class="inp" placeholder="you@company.com"></label><button class="btn-primary w-full !py-3">إرسال رابط الاستعادة</button><p class="text-sm text-ink-400 text-center"><a class="text-tiffany-400" href="#/login">العودة لتسجيل الدخول</a></p></form>';
var modeBadge=isRemote()
?'<div class="flex items-center gap-2 text-[11px] text-emerald-300 bg-emerald-500/10 border border-emerald-500/30 rounded-full px-3 py-1.5 mb-6 w-fit">'+icon('db','w-3.5 h-3.5')+' متصل بقاعدة بيانات Supabase — جلستك ستبقى محفوظة</div>'
:'<div class="flex items-center gap-2 text-[11px] text-amber-300 bg-amber-500/10 border border-amber-500/30 rounded-full px-3 py-1.5 mb-6 w-fit">'+icon('bolt','w-3.5 h-3.5')+' وضع محلي — الحسابات والبيانات تُحفظ على هذا الجهاز. <a href="#/setup" class="underline">اربط خادمًا حقيقيًا</a> للمزامنة</div>';
document.getElementById('app').innerHTML='<div class="min-h-screen grid lg:grid-cols-2">'
+'<div class="hidden lg:flex flex-col justify-between p-10 bg-ink-900 border-l border-ink-800 relative overflow-hidden"><div class="grid-bg absolute inset-0"></div>'
+'<a href="#/" class="relative flex items-center gap-2 font-display font-extrabold text-lg">'+brandHTML()+'</a>'
+'<div class="relative max-w-md"><h2 class="font-display font-extrabold text-3xl leading-snug mb-4">موظف AI لا ينام،<br><span class="text-tiffany-400">يرد على عملائك 24/7</span></h2><p class="text-ink-400 leading-7">Grounded AI + Knowledge Base معزولة لكل Agent + CRM تلقائي — يعمل متصلًا أو محليًا عند انقطاع الخادم.</p></div>'
+'<p class="relative text-xs text-ink-600">© إدارة ســوشـــيــــال</p></div>'
+'<div class="flex items-center justify-center p-6"><div class="w-full max-w-md fadeUp">'
+'<a href="#/" class="flex items-center gap-2 font-display font-extrabold text-lg mb-8 lg:hidden">'+brandHTML()+'</a>'
+'<h1 class="font-display font-extrabold text-2xl mb-1">'+titles[mode][0]+'</h1><p class="text-ink-400 text-sm mb-6">'+titles[mode][1]+'</p>'+modeBadge+form+'</div></div></div>';}
