function renderLanding(){
const app=document.getElementById('app');
app.innerHTML=
'<div class="fixed inset-0 grid-bg pointer-events-none"></div>'
+'<header class="relative z-20 glass sticky top-0"><div class="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">'
+'<a href="#/" class="flex items-center gap-2 font-display font-extrabold text-lg">'+brandHTML()+'</a>'
+'<nav class="hidden md:flex items-center gap-6 text-sm text-ink-300"><a class="hover:text-white" href="#how">كيف يعمل</a><a class="hover:text-white" href="#features">المميزات</a><a class="hover:text-white" href="#usecases">حالات الاستخدام</a><a class="hover:text-white" href="#pricing">الأسعار</a><a class="hover:text-white" href="#faq">الأسئلة</a></nav>'
+'<div class="flex items-center gap-2">'+(me()?'<button data-action="go" data-to="#/app" class="btn-primary">لوحة التحكم</button>':'<button data-action="go" data-to="#/login" class="px-4 py-2 text-sm text-ink-200 hover:text-white">تسجيل الدخول</button><button data-action="go" data-to="#/signup" class="btn-primary">ابدأ مجانًا</button>')+'</div></div></header>'
+'<section class="relative z-10 max-w-7xl mx-auto px-4 pt-14 pb-20 grid lg:grid-cols-2 gap-12 items-center"><div class="fadeUp">'
+'<div class="inline-flex items-center gap-2 text-xs text-tiffany-300 bg-tiffany-500/10 border border-tiffany-500/30 rounded-full px-3 py-1.5 mb-5">'+icon('spark','w-4 h-4')+' إدارة ســوشـــيــــال — منصة موظفي الذكاء الاصطناعي للأعمال</div>'
+'<h1 class="font-display font-extrabold text-4xl md:text-5xl leading-[1.3] mb-5">أضف <span class="text-tiffany-400">موظف AI</span> إلى موقعك خلال دقائق</h1>'
+'<p class="text-ink-300 text-lg leading-8 mb-8">أنشئ وكلاء ذكاء اصطناعي مدرّبين على بيانات عملك فقط — بدون اختراع معلومات — خصّص ويدجت الدردشة، وانسخ سطرًا واحدًا من الكود إلى موقعك.</p>'
+'<div class="flex flex-wrap gap-3"><button data-action="go" data-to="'+(me()?'#/app':'#/signup')+'" class="btn-primary !text-base !px-7 !py-3.5">'+(me()?'افتح لوحة التحكم':'ابدأ مجانًا')+'</button><button data-action="scroll" data-to="#how" class="btn-ghost !text-base !px-7 !py-3.5">شاهد كيف يعمل</button></div>'
+'<div class="flex flex-wrap gap-x-6 gap-y-2 mt-8 text-xs text-ink-400"><span class="flex items-center gap-1.5">'+icon('check','w-4 h-4 text-tiffany-500')+' Grounded AI — لا يخترع أسعارًا ولا منتجات</span><span class="flex items-center gap-1.5">'+icon('check','w-4 h-4 text-tiffany-500')+' معرفة معزولة لكل Agent</span><span class="flex items-center gap-1.5">'+icon('shield','w-4 h-4 text-tiffany-500')+' المفاتيح والأسرار لا تغادر الخادم</span></div></div>'
+'<div class="relative fadeUp"><div class="glass rounded-2xl p-4 shadow-soft">'
+'<div class="flex items-center gap-1.5 pb-3 border-b border-ink-800 mb-3"><span class="w-2.5 h-2.5 rounded-full bg-red-400"></span><span class="w-2.5 h-2.5 rounded-full bg-amber-400"></span><span class="w-2.5 h-2.5 rounded-full bg-emerald-400"></span><span class="ltr text-[11px] text-ink-500 px-2 font-mono">your-store.com</span></div>'
+'<div class="relative h-[460px] rounded-xl bg-ink-900 overflow-hidden"><div class="p-5 space-y-3 opacity-60"><div class="h-4 w-2/5 bg-ink-800 rounded"></div><div class="h-3 w-4/5 bg-ink-850 rounded"></div><div class="h-3 w-3/5 bg-ink-850 rounded"></div><div class="grid grid-cols-3 gap-3 pt-2"><div class="h-20 bg-ink-850 rounded-lg"></div><div class="h-20 bg-ink-850 rounded-lg"></div><div class="h-20 bg-ink-850 rounded-lg"></div></div></div>'
+'<div id="hero-widget" class="absolute inset-0 pointer-events-none"><div class="pointer-events-auto absolute inset-0"></div></div></div></div>'
+'<div class="absolute -z-10 -top-10 -left-10 w-64 h-64 bg-tiffany-500/20 blur-3xl rounded-full"></div></div></section>'
+'<section id="how" class="relative z-10 max-w-7xl mx-auto px-4 py-20"><h2 class="sec-title">كيف يعمل؟</h2><p class="sec-sub">أربع خطوات من التسجيل إلى موظف AI يتحدث مع عملائك.</p><div class="grid md:grid-cols-4 gap-5 mt-10">'
+[['bot','أنشئ Agent','الاسم والتعليمات واللهجة والنموذج ونطاق الإجابة.'],['book','اربط المعرفة','موقعك الإلكتروني، ملفاتك، أو نصوص يدوية — معزولة لكل Agent.'],['widget','خصّص الويدجت','كل الألوان والأبعاد والسلوك مع معاينة حية فورية.'],['code','انسخ الكود','سطر واحد في أي موقع — والمحادثات تصل للوحة التحكم.']].map(function(s,i){return '<div class="glass rounded-2xl p-6 hover:border-tiffany-500/40 transition relative"><div class="absolute top-4 left-4 font-display font-extrabold text-ink-700 text-2xl">'+(i+1)+'</div><div class="w-11 h-11 rounded-xl bg-tiffany-500/10 text-tiffany-400 border border-tiffany-500/30 flex items-center justify-center mb-4">'+icon(s[0])+'</div><h3 class="font-display font-bold mb-2">'+s[1]+'</h3><p class="text-sm text-ink-400 leading-6">'+s[2]+'</p></div>'}).join('')+'</div></section>'
+'<section id="features" class="relative z-10 bg-ink-900/60 border-y border-ink-800 py-20"><div class="max-w-7xl mx-auto px-4"><h2 class="sec-title">مميزات بمستوى عالمي</h2><p class="sec-sub">كل ما تحتاجه لتشغيل موظفين رقميين على موقعك.</p><div class="grid md:grid-cols-3 gap-5 mt-10">'
+[['shield','Grounded AI','يجيب فقط من قاعدة معرفتك. إذا لم توجد المعلومة يقول ذلك بوضوح — لا يخترع أسعارًا ولا منتجات ولا مواعيد.'],['book','Knowledge Base حقيقية','زحف موقعك (حتى 10 صفحات)، رفع PDF/DOCX/CSV/Excel، نصوص يدوية — مع بديل يدوي عند فشل الزحف.'],['users','CRM تلقائي','تصنيف العملاء (مشتري/مهتم/محتمل)، Lead Score من 0 إلى 100، ووسوم تلقائية تتطور مع المحادثة.'],['bolt','Widget قابل للتخصيص كليًا','ألوان الرأس والخلفية والرسائل، الأبعاد، الظل، الإطار، رسالة عدم الاتصال — معاينة حية.'],['chat','محادثات حية + Handoff','كل رسالة تظهر فورًا في لوحة التحكم، وتحويل بشري يوقف الـ AI حتى يعيد الموظف تفعيله.'],['db','عمل متصل أو محلي','مزامنة كاملة مع الخادم عند توفره، ووضع محلي آمن عند انقطاع الاتصال.']].map(function(f){return '<div class="rounded-2xl p-6 bg-ink-850 border border-ink-800 hover:border-tiffany-500/40 hover:-translate-y-0.5 transition"><div class="w-10 h-10 rounded-lg bg-tiffany-500/10 text-tiffany-400 flex items-center justify-center mb-4">'+icon(f[0])+'</div><h3 class="font-display font-bold mb-1.5">'+f[1]+'</h3><p class="text-sm text-ink-400 leading-6">'+f[2]+'</p></div>'}).join('')+'</div></div></section>'
+'<section id="usecases" class="bg-ink-900/60 border-y border-ink-800 py-20"><div class="max-w-7xl mx-auto px-4"><h2 class="sec-title">لمن بُنيت إدارة ســوشـــيــــال؟</h2><p class="sec-sub">أي نشاط يريد الرد الفوري على عملائه — على مدار الساعة.</p><div class="grid grid-cols-2 md:grid-cols-4 gap-4 mt-10">'
+['المتاجر الإلكترونية','الشركات','العيادات','المطاعم','الصالونات','العقارات','مكاتب الخدمات','مراكز التدريب'].map(function(u){return '<div class="rounded-xl bg-ink-850 border border-ink-800 p-5 text-center text-sm text-ink-200 hover:border-tiffany-500/40 hover:text-tiffany-300 transition">'+u+'</div>'}).join('')+'</div></div></section>'
+'<section id="pricing" class="max-w-7xl mx-auto px-4 py-20"><h2 class="sec-title">أسعار واضحة</h2><p class="sec-sub">ابدأ مجانًا مع 8 Agents، وترقَّ عندما تكبر.</p><div class="grid md:grid-cols-3 gap-5 mt-10">'
+Object.keys(PLANS).map(function(k){var p=PLANS[k];return '<div class="rounded-2xl p-7 border relative '+(k==='growth'?'border-tiffany-500/60 bg-tiffany-500/5 shadow-glow':'border-ink-800 bg-ink-850')+'">'+(k==='growth'?'<span class="absolute -top-3 right-6 text-[11px] font-bold bg-tiffany-500 text-ink-950 rounded-full px-3 py-1">الأكثر شيوعًا</span>':'')+'<h3 class="font-display font-bold text-lg">'+p.name+'</h3><div class="my-4"><span class="font-display font-extrabold text-4xl">'+p.price+'</span> <span class="text-ink-400 text-sm">ريال / شهريًا</span></div><ul class="space-y-2.5 text-sm text-ink-300 mb-7">'+p.feat.map(function(f){return '<li class="flex gap-2">'+icon('check','w-4 h-4 text-tiffany-500 mt-0.5')+' '+f+'</li>'}).join('')+'</ul><button data-action="go" data-to="#/signup" class="'+(k==='growth'?'btn-primary':'btn-ghost')+' w-full">'+(k==='free'?'ابدأ مجانًا':'اشترك')+'</button></div>'}).join('')+'</div></section>'
+'<section id="faq" class="max-w-4xl mx-auto px-4 pb-20"><h2 class="sec-title">الأسئلة الشائعة</h2><div class="mt-8 space-y-3">'
+[['هل يخترع الـ AI معلومات غير موجودة؟','لا. يعمل بمبدأ Grounded AI الصارم: يجيب فقط من قاعدة معرفتك، وإذا لم يجد المعلومة يرد نصًا: «عذراً، هذه المعلومة غير متوفرة لدي حالياً، هل أستطيع تحويلك لأحد موظفي الدعم؟».'],['ماذا لو انقطع الاتصال بالخادم؟','يستمر التطبيق بالوضع المحلي تلقائيًا: بياناتك تُحفظ على جهازك وتعاد المزامنة بضغطة زر عند عودة الاتصال.'],['ماذا لو فشل زحف رابط موقعي؟','يفتح لك صندوقًا لتلصق محتوى الموقع يدويًا، فيُضاف فورًا كمصدر معرفة جاهز.'],['ماذا يحدث عندما يطلب العميل موظفًا؟','تتحول المحادثة إلى Human Handoff ويتوقف الـ AI عن الرد حتى يعيد الموظف تفعيله.'],['هل بياناتي معزولة؟','نعم، سياسات RLS على مستوى قاعدة البيانات تربط كل سجل بمساحة عملك فقط، ومعرفة كل Agent معزولة عن غيره.']].map(function(f){return '<details class="faq glass rounded-xl group"><summary class="flex items-center justify-between cursor-pointer px-5 py-4 font-semibold text-sm list-none">'+f[0]+'<span class="text-tiffany-400 transition group-open:rotate-45 text-xl leading-none">+</span></summary><p class="px-5 pb-5 text-sm text-ink-400 leading-7">'+f[1]+'</p></details>'}).join('')+'</div></section>'
+'<section class="max-w-5xl mx-auto px-4 pb-24"><div class="rounded-3xl p-10 md:p-14 text-center relative overflow-hidden border border-tiffany-500/30 bg-gradient-to-b from-tiffany-500/15 to-transparent"><h2 class="font-display font-extrabold text-3xl md:text-4xl mb-4">جاهز توظّف أول موظف AI لديك؟</h2><p class="text-ink-300 mb-8">انضم إلى إدارة ســوشـــيــــال الآن وأنشئ وكيلك الأول خلال دقائق — مجانًا مع 8 Agents.</p><button data-action="go" data-to="#/signup" class="btn-primary !text-base !px-9 !py-4">ابدأ مجانًا الآن</button></div></section>'
+'<footer class="border-t border-ink-800 py-10 text-center text-sm text-ink-500"><div class="flex items-center justify-center gap-2 mb-3">'+brandHTML()+'</div>منصة إدارة ســوشـــيــــال لموظفي الذكاء الاصطناعي — كل الحقوق محفوظة '+new Date().getFullYear()+'</footer>';
var heroHost=document.querySelector('#hero-widget .pointer-events-auto');
if(heroHost){
var demoW=defWidget('','مساعد النخبة');
demoW.width=300;demoW.height=340;demoW.radius=14;demoW.avatar=AV_LOCAL[0];demoW.badge=true;
var heroAgent={name:'مساعد النخبة',welcome:'أهلًا بك في متجر النخبة 👋 اسألني عن الأسعار أو الشحن.',fallback:NO_INFO_MSG,avatar:AV_LOCAL[0]};
mountWidget(heroHost,demoW,heroAgent,{fixed:false,credit:false});}}
